name:                sequence
version:             0.1.0.0
github:              "oskarek/sequence"
license:             BSD3
author:              "Oskar Ek"
maintainer:          "oek@kth.se"
copyright:           "Copyright (c) 2017 Oskar Ek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/oskarek/sequence#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- criterion

library:
  source-dirs: src

executables:
  sequence-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequence

tests:
  sequence-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequence
